version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: balkanetflix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: balkanetflix_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 128mb

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: balkanetflix-adminer
    ports:
      - "8888:8080"
    depends_on:
      - db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: balkanetflix-server
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: balkanetflix-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

volumes:
  postgres_data:
