[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"

[deploy]

releaseCommand = "npx prisma migrate deploy"

startCommand = "npm run start" # sau "node dist/server.js"

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10